[package]
name = "Watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riven = "2.17.0"
tokio = "1.27.0"
tui = "0.19.0"
