name: Rust

on:
  push:
    branches: [ "main",  "switch-to-ratatui"]
  pull_request:
    branches: [ "main", "switch-to-ratatui"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
